name: daily
on:
  push:
    branches:
      - dev
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '15'
      - run: yarn
      - run: yarn generate

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.REPO_TOKEN }}
          publish_branch: master
          publish_dir: ./public
          keep_files: true
          allow_empty_commit: false

  issue:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.modified, 'issue-template.md')"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        with:
          filename: issue-template.md
      - run: 'echo Created issue number ${{ steps.create-issue.outputs.number }}'
      - run: 'echo Created ${{ steps.create-issue.outputs.url }}'
