name: daily
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: dev
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: yarn
      - run: yarn generate

      - uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.REPO_TOKEN }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
        with:
          keepFiles: true
          emptyCommits: false
