name: 'daily'
on:
  push:
  schedule:
    - cron: '0 16 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@master
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
        run: npm start

        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: README.md